Endale.auth
smyja/pricebunny-fe pull request #1
Opened 2023-08-03 07:49 UTC by Endalebob

This pull request encompasses the following key enhancements to the project:

Configured Redux for streamlined state management.
Implemented authentication logic.
Developed the logic for user login functionality.
Created UI components for signup and forget password and confirm password change.
Implemented the logic for user signup, including handling the forget password and confirm password change processes.
![signup](https://github.com/smyja/pricebunny-fe/assets/95867374/efdce7e1-2da5-4b2b-b12f-edb1b4d16949)
![confirm](https://github.com/smyja/pricebunny-fe/assets/95867374/9c0de95a-234d-4d20-8000-5f73ce70b1e3)
![forgetpass](https://github.com/smyja/pricebunny-fe/assets/95867374/57dd72de-0db5-4f94-b783-61cb1dc632bf)

2023-08-03 09:38 UTC, smyja requested changes

2023-08-03 09:38 UTC, smyja commented on store/auth-api.js
> +          url: "/Profile/me",
the endpoint is /user

2023-08-03 09:38 UTC, smyja commented on store/auth-slice.js
> +      setCookie("refresh", action.payload.refresh);
check the examples i sent to see how it was done for token refresh and verify. the endpoint is available already

2023-08-03 09:53 UTC, Endalebob commented on store/auth-slice.js
> +      setCookie("refresh", action.payload.refresh);
will do.

2023-08-03 11:07 UTC, smyja requested changes

2023-08-03 11:07 UTC, smyja commented on store/auth-api.js
> +          return { url: "/logout", method: "POST" };
there's a logout endpoint in the docs already. add a logout button to the dashboard page to see if it works.

2023-08-03 11:07 UTC, smyja commented on store/auth-slice.js
> +  role: getCookie("role") || "",
which endpoint are you expecting this from so i can add it.

2023-08-03 11:07 UTC, smyja commented on store/auth-slice.js
> +  profilePicture: getCookie("profilePicture") || "",
same thing

2023-08-03 15:00 UTC, smyja requested changes
left a few more. mark them as resolved once you're done.

2023-08-03 15:00 UTC, smyja commented on app/login/page.tsx
> +  //====================================================================================================
no need for //====, just remove my code. Also remove unused imports, use a linter like eslint.

2023-08-03 15:00 UTC, smyja commented on app/login/page.tsx
> +  const handleSignin = async (values) => {
add a type for this since its typescript something like this.  
```
type FormValues = {
    email: string;
    password: string;
  };
  
  const handleSignin = async (values: FormValues) => {
    signInUser(values);
  };
```
[Eslint ](https://eslint.org/) would show the error already.

2023-08-03 15:33 UTC, smyja requested changes

2023-08-03 15:33 UTC, smyja commented on app/login/page.tsx
> +    signInUser(values);
setLoading(true) then false when there's an error

2023-08-04 18:02 UTC, merged

2023-08-04 18:02 UTC, smyja commented
great job